apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      project.cpaas.io/name: stwu
      service.cpaas.io/name: deployment-nodejs-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cpaas.io/creator: admin@cpaas.io
      creationTimestamp: null
      labels:
        project.cpaas.io/name: stwu
        service.cpaas.io/name: deployment-nodejs-demo
    spec:
      affinity: {}
      containers:
        - image: 192.168.14.254/tinyunshe/nodejs-demo:19cd7b99
          imagePullPolicy: IfNotPresent
          name: nodejs-demo
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: pub-harbor-6dy2hc.kauto.docfj
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
